version: 2
updates:
  - package-ecosystem: github-actions
    rebase-strategy: "auto"
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    rebase-strategy: "auto"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      dev-deps:
        dependency-type: development
      prod-deps:
        dependency-type: production
