- name: 'backlog'
  color: '7ef7ef'
- name: 'bug'
  color: 'd73a4a'
- name: 'chore'
  color: 'ffffff'
- name: 'ci'
  color: '0075ca'
- name: 'dependencies'
  color: '276bd1'
- name: 'discussion'
  color: 'b6b1f9'
- name: 'documentation'
  color: '0075ca'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'feature request'
  color: 'fcf95a'
- name: 'good first issue'
  color: '7057ff'
- name: 'help wanted'
  color: '008672'
- name: 'in progress'
  color: 'ffccd7'
- name: 'in review'
  color: 'aed5fc'
- name: 'invalid'
  color: 'e4e669'
- name: 'need repro'
  color: 'c66037'
- name: 'performance'
  color: '80c042'
- name: 'priority:high'
  color: 'fc1423'
- name: 'question'
  color: 'd876e3'
- name: 'refactor'
  color: '1d637f'
- name: 'regression'
  color: 'ea8785'
- name: 'tests'
  color: 'f06dff'
- name: 'utility'
  color: '80c042'
- name: 'wontfix'
  color: 'ffffff'
